# Generated by Django 5.2.8 on 2025-12-21 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_alter_flashcardset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardprogress',
            name='predefined_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flashcardprogress',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcards.flashcardset'),
        ),
    ]
